version: "3"
services:
  promo_db:
    container_name: promo_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=promo_admin
      - POSTGRES_PASSWORD=NijO9faBZgKjRvA
      - POSTGRES_DB=promo_db
    image: postgres:15.4-alpine3.17
    restart: always
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    networks:
      - app-network
    depends_on:
      - promo_db
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"

  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"

  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    depends_on:
      - frontend

networks:
  app-network:
    driver: bridge

volumes:
  shared-data:
