import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import '@assets/styles/global.scss';
import './ShopLayout.scss';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <body className={montserrat.className}>
        <div className="shop-layout">
          <main className="shop-layout__page">{children}</main>
        </div>
      </body>
    </html>
  );
}
