import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@assets/styles/global.scss';
import './ProfileLayout.scss';
import ProfileHeader from '@profileComponents/ProfileHeader/ProfileHeader';
import { getSession } from '@/typeorm/getSession';
import RefCodeHandler from '@shopComponents/RefCodeHandler/RefCodeHandler';
import { redirect } from 'next/navigation';
import { AntdRegistry } from '@ant-design/nextjs-registry';

const montserrat = Inter({ subsets: ['latin', 'cyrillic', 'cyrillic-ext'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getSession();
  if (!session.isLoggedIn) {
    redirect('/');
  }

  return (
    <html lang="ru">
      <body className={montserrat.className}>
        <AntdRegistry>
          <div className="profile-layout">
            <ProfileHeader />
            <main className="container profile-layout__page">{children}</main>
          </div>
        </AntdRegistry>
      </body>
      <RefCodeHandler />
    </html>
  );
}
